services:
#    admin.example:
#        class: App\App\Bundles\AdminBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    #form.type.collection:
    #  class: App\Bundles\AdminBundle\Form\Type\BootstrapCollectionType
    #  tags:
    #        - { name: form.type, alias: bootstrap_collection }
#
    #form.ckeditor:
    #    class: App\Bundles\AdminBundle\Form\Type\CkeditorType
    #    tags:
    #        - { name: form.type, alias: ckeditor }